### ISSUE TITLE
OARS v1 xAPI Work

### ISSUE THREAD

**Issue by bmtcril** [openedx/event-routing-backends#261]
This epic holds all of the work that's blocking OARS v1 adoption:

- [x] https://github.com/openedx/event-routing-backends/issues/258
- [x] https://github.com/openedx/event-routing-backends/issues/259
- [x] https://github.com/openedx/event-routing-backends/issues/260

**Comment by bmtcril** [comment]
These issues are complete, closing!
